name = "PaperMod"
license = "MIT"
licenselink = "https://fclapton26.github.io/PaperMod//blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://fclapton26.github.io/PaperMod/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.112.4"

[author]
  name = "Ada Teange"
  homepage = "https://fclapton26.github.io/PaperMod/"

# If porting an existing theme
[original]
  name = "Paper"
  author = "nanxiaobei"
  homepage = "https://fclapton26.github.io/PaperMod/"
  repo = "https://github.com/fclapton26/PaperMod"
